#!/bin/sh

echo ========== Cleaning Bower ==========
echo ====================================
echo  
rm -rf public/bower_components
bower cache clean
rc=$?
if [ $rc != 0 ] ; then
    echo Failed to clean the bower cache
    exit $rc
fi

echo   
echo ========== Installing Bower Dependencies ==========
echo ===================================================
echo
cd public

bower install
rc=$?
if [ $rc != 0 ] ; then
    echo Failed to install bower dependencies
    exit $rc
fi

cd ..

echo   
echo ========== Running grunt ==========
echo ===================================
echo   
npm run build
rc=$?
if [ $rc != 0 ] ; then
    exit $rc
fi
